spring:
  ai:
    openai:
      api-key: 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